# You will replace these two values in Phase 3
sonar.projectKey=Mryash7803_user-service-app
sonar.organization=mryash7803

# This points to your source code directory (use . for the root directory)
sonar.sources=.

# Exclude node_modules or infrastructure files from the code quality scan
sonar.exclusions=node_modules/**, helm/**, k8s/**
