replicaCount: 2

image: 
  repository: mryashdoc/user-service
  tag: "17efe53711f132aef47b0bfa9df5ad27647b91de"
  pullPolicy: IfNotPresent


service:
  type: ClusterIP
  port: 80
 

database:
  host: postgres-service
  port: 5432

