replicaCount: 2

image: 
  repository: mryashdoc/user-service
  tag: "5a1fcb08b59cc4468ff9c992dc65778111499240"
  pullPolicy: IfNotPresent


service:
  type: ClusterIP
  port: 80
 

database:
  host: postgres-service
  port: 5432

