replicaCount: 2

image: 
  repository: mryashdoc/user-service
  tag: "cdf04b8af4b59def47966649747e6fc641e93f2d"
  pullPolicy: IfNotPresent


service:
  type: ClusterIP
  port: 80
 

database:
  host: postgres-service
  port: 5432

