apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Mryash7803/user-service-app.git'
    targetRevision: EAD
    path: helm/user-service
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


